name: 🚀  Minerador Automático Edge Pro
on:
  # Agendamento: Roda às 08:00 e 18:00 (Horário de Brasília)
  schedule:
    - cron: '0 11,21 * * *' 
  
  # Libera o botão "Run Workflow" no site do GitHub
  workflow_dispatch: 

jobs:
  executar_minerador:
    runs-on: ubuntu-latest
    
    steps:
      - name: 1. Baixando os arquivos do GitHub
        uses: actions/checkout@v3

      - name: 2. Preparando o ambiente Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 3. Instalando as bibliotecas necessárias
        run: |
          pip install requests psycopg2-binary pytz

      - name: 4. Rodando o Minerador Total
        env:
          # Puxa o link do banco que você salvou nos Secrets do GitHub
          DB_URL: ${{ secrets.DB_URL }}
        run: python worker_saas.py

        