name: Minerador Oficial

on:
  workflow_dispatch:

jobs:
  executar:
    runs-on: ubuntu-latest
    
    # MUDANÇA: Variáveis no topo para garantir leitura
    env:
      DB_URL: "postgresql://postgres.vbxmtclyraxmhvfcnfee:MudarAgora2026Paraiba@aws-1-sa-east-1.pooler.supabase.com:6543/postgres"
      TELEGRAM_TOKEN: "8344469814:AAHvhEKG9_6qfaPc-1gdjYdcBGn6qdcfFeg"
      TELEGRAM_CHAT_ID: "1343274781"

    steps:
      - name: Baixar Codigo
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar Bibliotecas
        run: pip install requests psycopg2-binary pytz

      - name: Rodar Minerador
        run: python worker_saas.py